#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true)

if [ -n "$GO_FILES" ]; then
  echo "=> Running go fmt on staged files"
  for file in $GO_FILES; do
    go fmt "$file"
    git add "$file"
  done
fi
